name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK and CMake
        run: |
          sdkmanager "ndk;25.2.9519653"
          sdkmanager "cmake;3.22.1"

      - name: Unzip project
        run: unzip KeyMapperProV2.zip

      - name: Make gradlew executable
        run: chmod +x KeyMapperV2/gradlew

      - name: Build APK
        run: cd KeyMapperV2 && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KeyMapperPro-APK
          path: KeyMapperV2/app/build/outputs/apk/debug/app-debug.apk
